data_source adventureworks:
  type: postgres
  connection:
    host: localhost
    username: postgres
    password: secret
    database: postgres
    schema: public

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: 93ac3d5c-24b3-46d5-9f4d-92a02af04d96
  api_key_secret: RZvf96WIui4vopyFm8NMcww1wAarMi8AH7wuWzHniJFHjIV7Ik4Onw